### ISSUE TITLE
[TCOTD2] Pendant makes the game too easy

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#109]
The whole point of the nightmares was to add a fuckton of tension - you don't know how much time you'd have left before you'd be fucked, basically.

Now with the pendant, it's trivial to just avoid nightmares completely. As soon as it looks very red, one would have the tendency to just go to the nearest shelter and camp there.

I propose the pendants be a limited-use powerup.

Normal = 2 uses
Hard = 1 use
Nightmare = 1 use, and the pendant breaks halfway

The pendant will break after its been used up. You'll be on your own from then on.

**Comment by Blue-Shadow** [comment]
Not too keen on the limited use thing, because I'll just end up not using it at all since I wouldn't know what's the best time to use it.

How about keeping it as is (unlimited) while giving it a random chance of breaking on all difficulties, but only after surviving a set number of nightmares (the first nightmare, after the spider boss, could be made not to count towards that, if possible)?

**Comment by Tormentor667** [comment]
I definitely agree that it makes the game too easy and that it needs some kind of limitation. 

What about instead of being limited use, it gets activated as soon as you collect it and after two times nightmares it automatically breaks?

**Comment by nashmuhandes** [comment]
Yeah, if it's going to break, I'd rather it be a fixed amount, rather than be at the mercy of a random number generator

**Comment by nashmuhandes** [comment]
Done. If a player owns a pendant, it will break after surviving a number of nightmares, determined by difficulty:

Normal: 3 nightmares
Hard: 2 nightmares
Nightmare: 1 nightmare
