### ISSUE TITLE
[TCOTD2] Door of dark room in the mansion is relatively bright

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#120]
![Screenshot_Doom_20230118_014546](https://user-images.githubusercontent.com/4287687/213052815-0ef1e85e-38e8-469d-adc9-a12b24134f5e.png)

**Comment by nashmuhandes** [comment]
I think this is caused by the polyobject taking the lighting of the control sector? I dunno, just a guess.

**Comment by Blue-Shadow** [comment]
No, it's actually coming from the sector the door is in, the one you see highlighted below. The sector has a light level of 105.

![Untitled](https://user-images.githubusercontent.com/4287687/213427871-64bbfdde-2c22-4902-8797-07be0dff2c0d.jpg)

**Comment by Ozymandias81** [comment]
Since the accessible room has scriptified lights, I tagged as well the door sector with 213 and put brightness to 0, hopefully this won't turn the door not easy to be noticed (shouldn't).

![image](https://user-images.githubusercontent.com/11136108/213442312-19a17a21-63f0-4f56-a869-06428a52685d.png)
