### ISSUE TITLE
[TCotD2] No cutscenes (discussion)

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#132]
After playing the game now and encountering the dogs again, I have the feeling that the cutscene slows down the pace and makes the encounter less of a surprise or a treat and more like a scripted event. 

Personally I am always a big fan of cutscenes which do not feel like a cutscene because you can still move and look around because the camera hasn't changed.

What about walking into the area, the dogs are asleep (we could recycle one of the death frames here) and as soon as you see them, they wake up and attack you?

**Comment by nashmuhandes** [comment]
My opinion here will be biased, as I am the one who's advocating for these scripted cutscenes after all (in the name of "production values" :P) but what I can do very quickly, with very little effort, is make the cutscenes skippable immediately.

**Comment by Tormentor667** [comment]
It's less a question of production values - I do get the point of having some kind of next-gen feature - but for me it's always a question towards the gameflow. How hard would it be to go both ways somehow with a way to choose as a player? E.g. "Enable Cutscenes as an option"?

**Comment by nashmuhandes** [comment]
Sure, it wouldn't be too much work to add a "no boss cutscene" option in the menu. But I must insist that the cutscenes be enabled to on by default to showcase the differences of the remaster. In my opinion this is the "junk food" that impresses players today. At least with the toggle-able option, players aren't forced to have it on and they have a choice.

**Comment by Tormentor667** [comment]
That's a fine compromise then.

**Comment by Blue-Shadow** [comment]
While working on this, I realized that the cutscene isn't needed anymore here. You see, the reason it was added was to remedy issue #100. Since then, the encounter has changed: the barn is initially closed until you get the shotgun. Once you do that, you hear dog barking sounds and you get an objective to investigate. As you approach the now-opened barn, all that is need is for the boss music to kick in, the barriers to appear and the dogs to burst out and attack. There is no need for a cutscene!

So that's what I did in 69993ad93b34c068edf270eb2a7844da147729c3. I disabled the cutscene in favor of a seamless experience. I didn't get rid of any code related to the cutscene. It's all there. Maybe a cutscene could be used for summoning the final boss after all the artifacts are in place...

**Comment by nashmuhandes** [comment]
> So that's what I did in https://github.com/Realm667/Re-Releases/commit/69993ad93b34c068edf270eb2a7844da147729c3. I disabled the cutscene in favor of a seamless experience. I didn't get rid of any code related to the cutscene. It's all there. Maybe a cutscene could be used for summoning the final boss after all the artifacts are in place...

Agreed, I can move the cutscene to the final boss summoning instead, since it's a big deal. And, of course, I'll make it optional

**Comment by Tormentor667** [comment]
I agree with your suggestions here

**Comment by Tormentor667** [comment]
Closing this and reopening a new issue, just for correctness.
