### ISSUE TITLE
[TCotD2] Scaling of the final credits letter is wrong

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#162]
![grafik](https://user-images.githubusercontent.com/10298439/218323254-81db1aa6-1710-4b03-8ddd-18e3e19de413.png)

**Comment by nashmuhandes** [comment]
This needs special handling because technically the game has ended, and it shouldn't be presented as a standard in-game letter. In technical terms, it shouldn't be handled via the in-game letter-reader UI.

I have an idea on how to tackle this, but first, I'd like to ask - what font exactly is used in this letter?

**Comment by Tormentor667** [comment]
Isn’t this displayed as png with SETFONT anyway? If you ask me we can keep it like that. 

…my guess is that due to the hires replacement the scale is doubled and not fitting into the screen anymore. Changing “sethudsize” might already fix it.

**Comment by nashmuhandes** [comment]
I have a surprising idea to solve this problem. Please do not attempt to fix the script. :)

**Comment by Tormentor667** [comment]
Curiosity grows 😀

**Comment by nashmuhandes** [comment]
Still on plan. Will implement something really cool that's never seen before in GZDoom mods

**Comment by Tormentor667** [comment]
> Still on plan. Will implement something really cool that's never seen before in GZDoom mods

Now I am curious

**Comment by nashmuhandes** [comment]
As per the original issue, the scaling is technically now corrected so I'm closing this.
