### ISSUE TITLE
[TCOTD2] Poisening suggestions

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#169]
Regarding the design of the poison effect, I'd suggest

- making the hud color green to match the poison attack color
- add some kind of visual border effect (same as low health, just in green) so the player notices that he is poisened.

@Blue-Shadow

**Comment by Blue-Shadow** [comment]
If an on-screen effect similar to the low health one is added, then I don't see a need for the health counter on the HUDs to change color anymore, as it's meant to be the indicator for being poisoned.

The reason I picked purple and not green, is because the alternative HUD already uses green to indicate "good" condition (health between 50 and 100 inclusive). Also, it isn't uncommon for purple to be associated with poison.

**Comment by Tormentor667** [comment]
I simply think that the hud design and the color the vulgar projectiles clashes. We could also recolor the vulgar for that case. Or maybe even consider a second vulgar with poisonous projectiles in purple?

**Comment by Blue-Shadow** [comment]
[Addressed](https://github.com/Realm667/Re-Releases/commit/9248f5a0ddc71ab282bb3e9797ae9e28b972e3a1).

**Comment by Tormentor667** [comment]
I like it as it is now, but I am not sure yet if you get the first antidote too late (you only can get it in the bar's upper level as soon as you have the lantern). What do you mean?
