### ISSUE TITLE
[TCotD2] Bullets not harming Nightmares and Ghosts?

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#194]
I noticed that shooting ghosts and nightmares doesn't kill them. I mean, if you can't kill them with the pitchfork and also not with guns, how are you supposed to kill them? @Blue-Shadow

**Comment by Blue-Shadow** [comment]
For the Nightmare, just like before, it's vulnerable to attacks only when it reveals itself, i.e. when it attacks you. It's best to hit it with a double-barrel blast from the shotgun to finish it quickly.

For the Wraith, you're probably failing to hit it since it has such a small radius. I increased it in 74fdab7bfd46ca47b2d8b24a75916f1f1b11c4e2, so it should now be easier to hit.

**Comment by Tormentor667** [comment]
But both are vulnerable to the pitchfork yes?

**Comment by Blue-Shadow** [comment]
No, the ghost enemies can neither be damaged with the fists or pitchfork (stab and throw). That's intentional.

**Comment by Tormentor667** [comment]
Do you think a hint regarding this somewhere would be of use?

**Comment by Blue-Shadow** [comment]
Probably. Otherwise players would report it as a bug, and when you tell them it's intentional, they would tell you that a hint should've been added about it.

**Comment by Tormentor667** [comment]
Added some notes to the city
