### ISSUE TITLE
[TCOTD2] Bath house/toilet door inconsistency

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#231]
The door opens outwards (push) if you're inside, whereas it opens inwards (pull) if you're outside. While this makes sense, it's also inconsistent with the other doors, where they always open outwards (push) regardless of which side of the doors you are at.

Does that make sense?

**Comment by nashmuhandes** [comment]
Yes, I actually did deliberately make it that way, because I didn't want the door to block the vent if you come in from outside. I was fully aware that this would have been a weird inconsistency compared to the other doors in the map.

Maybe I'll turn the door into a sliding door instead to solve this problem.

**Comment by nashmuhandes** [comment]
Changed the door to sliding in https://github.com/Realm667/Re-Releases/commit/3ec530689d3ba659ea7696b91ae7168fad19e955
