### ISSUE TITLE
[TCOTD2] Wraiths are able to resurrect the scripted zombies in the cemetery

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#243]
Not sure if this is intended behavior but one time, this wraith wandered into the burial, resurrected the zombie, and the zombie wandered outside, slightly ruining the scripted sequence with the shotgun pickup.

**Comment by Tormentor667** [comment]
Definitely not intended.

**Comment by Blue-Shadow** [comment]
Partially addressed in 84fdebccc569f1695f55c82457108040505e85b0. I say "partially" because the map's WAD needs changing. What needs doing:
+ Set the `user_ReviveSelfOnly` field to `true` on those zombies in the map editor.
+ Replace the `Thing_Raise` special by `TCOTD_RaiseThing` function. This function does an extra little thing where it sets the field to `false` after the monsters are brought back so that they can be revived by other monsters like normal after the event.

Apart from the zombies in the cemetery, the zombies (butchers) in the hospital could do with the same treatment, since the hospital is close to the cemetery and the zombies themselves are lying in front of the exit door to the hospital. A wraith could potentially wander into the hospital from the cemetery and revive one of them.

**Comment by nashmuhandes** [comment]
@Blue-Shadow ok, thanks. Will see to it after @Tormentor667 is done with the swamp optimization pass

**Comment by nashmuhandes** [comment]
Fixed with https://github.com/Realm667/Re-Releases/commit/a8890a08f9a1244443c866e26cceee46b5a15b43
