### ISSUE TITLE
[TCOTD2] No warp effect on swamp water (OpenGL ES)

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#261]
You can only see the warping effect if using OpenGL, and I'd imagine Vulkan as well, but not OpenGL ES.

Note that I wouldn't have reported this, but seeing Nash's commit message [here](https://github.com/Realm667/Re-Releases/commit/898344d1faa0e7603f55b661c83f59df68325cde) prompted me to do so.

**Comment by nashmuhandes** [comment]
This will probably be a [won't fix] because none of the shaders work in GLES.

Additionally, had to make the fog actors also always be invisible in GLES because the shader doesn't work, which unfortunately results in the fog blocking the view too much. This is fine anyway, as multiple translucent overdrawn sprites would probably murder performance for machines low-end enough to actually require GLES.
