### ISSUE TITLE
[TNTx] Spectre has no typical NashGore blood effect

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#299]
![grafik](https://github.com/Realm667/Re-Releases/assets/10298439/c7831a73-aa64-407e-b1d8-1f4678da42f1)

This happens by the way for all re-releases. Does it have something to do with the update from regular NashGore to the NashGore vengeance edition? 

I would be able to remove the old nashgore but unfortunately there is just an old forum thread here with the file link being dead: https://forum.zdoom.org/viewtopic.php?t=11545

**Comment by Tormentor667** [comment]
Nevermind, found the original old gore. I will try to remove it from TNT3 now.

[old_nashgore.zip](https://github.com/Realm667/Re-Releases/files/13992174/old_nashgore.zip)

**Comment by Ozymandias81** [comment]
I am trying everything but it seems to be a limit with the modern version of Nashgore, the "old" one portions of codes works good because they spawn gibs and blood directly from a custom death/crash sequence, while instead model-based stuff keeps using only the bloodcolor given and not the renderstyle

**Comment by Ozymandias81** [comment]
Maybe @nashmuhandes knows how to help us with this issue, I noticed a portion of code inside the NashGoreBloodPlane zscript code that seems to try get the renderstyle and put the Shaded for the model
