### ISSUE TITLE
[TCotD2] Remove HUD from final credit roll

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/Re-Releases#64]
and make sure to give the player enough health to avoid the heart-beat effect when at low health - maybe something @Ozymandias81 can take care.

**Comment by Ozymandias81** [comment]
Alright it is done, but we can still open the map because of the FROZEN flag how is set (we must be able to press Use).
Also it looks that you missed something here @Tormentor667 , which is the script for that letter?
![image](https://user-images.githubusercontent.com/11136108/203833494-db218584-b529-49ad-a2b5-fd1d212cf6c0.png)

**Comment by Tormentor667** [comment]
Found the missing script, fixed it.
