### ISSUE TITLE
[TCOTD2] AI upscaled textures have a LOT of seams + other problems inside

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#84]
Original (no seams)

![image](https://user-images.githubusercontent.com/4926156/211622392-c778c56c-3620-4b0d-92f1-d2a684dc3da7.png)

Upscaled (lots of hard seams at the edges)

![image](https://user-images.githubusercontent.com/4926156/211622418-f3a8cce1-9d3f-418b-9cf1-c7c891f80260.png)

I'm not convinced these AI upscaled textures are enhancing the look of the game. If anything, I think they make the textures look worse (like most anything related to AI, unsurprisingly).

Open my images in a full, new window. Also, these seams are even much more noticable in-game. They almost look like misaligned textures, sometimes.

Unless someone wants to go through ALL of these upscaled textures to clean up those seams...

Lastly, this is just one example - I have checked that almost all, if not all, of the upscaled textures have the seams.

**Comment by nashmuhandes** [comment]
Another argument against this is that VRAM usage increases quite a bit with more high res textures all being loaded in a single map.

This really should be a separate and optional mod, rather than built into the base mod.

**Comment by Ozymandias81** [comment]
@Tormentor667 thought so that both models and AI are not necessary for the re-release (except those fancy voxels, which are good and only a couple). I suggest to revert tx changes and instead strip down doubles to reduce filesize of the wad, changing on map each replaced tx this way. Hires tx also prevent some textures to animate in game, I do remember seeing the ABLOOD scrolling walls not scrolling after the hires addition (could be related to short/long names too)

**Comment by Ozymandias81** [comment]
I'll leave the hires removal (beside liquids and sky) to @Tormentor667

**Comment by Tormentor667** [comment]
I am okay with removing them again (except the skybox one)

**Comment by nashmuhandes** [comment]
Fixed
