### ISSUE TITLE
[TCOTD2] Visibility issue

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#92]
It appears that the monsters in the room you see in the screenshot can't see, thus attack, the player if he or she is standing where I am standing. However, the player is free to shoot and kill these monsters, which feels kind of a cheap way to get rid of them.

![Screenshot_Doom_20230112_091335](https://user-images.githubusercontent.com/4287687/212007009-24c7974e-329a-427f-8444-094bf7a3e411.png)

**Comment by nashmuhandes** [comment]
These two areas are connected via portals. I have no idea how to fix this as I basically ignore portals in my mapping career completely, LOL.

Maybe someone else can take a look, after I give the all-clear that I'm done with editing the map WAD.

**Comment by Blue-Shadow** [comment]
Could the area not be re-worked? If that's a no, then the monsters could be removed entirely.

**Comment by Tormentor667** [comment]
I am not sure if it is possible to fix the issue. I can live with removing the monster though.

**Comment by nashmuhandes** [comment]
Fixed by removing the cultists, and adding a little surprise inside the vent :)

**Comment by nashmuhandes** [comment]
![Screenshot_Doom_20230114_045753](https://user-images.githubusercontent.com/4926156/212418280-26451cd2-6bff-4269-b5dc-70e74fae6743.png)

Found another spot with the same issue (concerning this being an "unreal" portal). This one is more serious and it's not ideal to simply remove enemies.

Coincidently, this is also why torches are broken (as mentioned in https://github.com/Realm667/Re-Releases/issues/96) - it's not that the torch code is portal-unfriendly - it's simply because this being an "unreal" portal, causes the distance check of the torches to break.

**Comment by Tormentor667** [comment]
Considering the setup of the portals I simply say that this can’t be fixed. What about leaving as is and just rearrange the enemies to make it less obvious?

**Comment by nashmuhandes** [comment]
> Considering the setup of the portals I simply say that this can’t be fixed. What about leaving as is and just rearrange the enemies to make it less obvious?

Yeah, technically there is only 1 cultist placed at the entrance, we can remove him. Keep the fights inside the rooms upstairs

**Comment by nashmuhandes** [comment]
Fixed (moved the enemies around so no fights occur at the downstairs mansion hall)
